using System.Collections;
using System.Collections.Generic;
using System.Linq;
using AirSticker.Runtime.Scripts.Core;
using AirSticker.Runtime.Scripts.Core.Jobs;
using Unity.Jobs;
using UnityEngine;
using UnityEngine.Events;

namespace AirSticker.Runtime.Scripts
{
    /// <summary>
    ///     Mesh decal projector. <br />
    ///     This decal projector has the following characteristics. <br />
    ///         1. Fast, spike-free projection of mesh decals. <br />
    ///         2. Draw mesh decals with fewer draw calls. <br />
    ///         3. It works in both URP and BRP. <br />
    ///         4. All user-defined materials can be used. <br />
    ///         5. Mesh decals can be skin animated. <br />
    /// </summary>
    public sealed class AirStickerProjector : MonoBehaviour
    {
        public enum State
        {
            NotLaunch,
            Launching,
            LaunchingCompleted,
            LaunchingCanceled
        }

        [SerializeField] private float width; // Width of the decal box.
        [SerializeField] private float height; // Height of the decal box.
        [SerializeField] private float depth; // Depth of the decal box.
        [SerializeField] private GameObject[] receiverObjects; // The receiver object that will be pasted decal.
        [SerializeField] private float zOffsetInDecalSpace = 0.005f ; // The Z offset of the decal space from the receiver surface.
        [SerializeField]
        private Material decalMaterial; // The decal material that will be pasted to the receiver object.

        [Tooltip("Decal meshes are shared within the same group. Split groups to remove decals separately.")]
        [SerializeField]
        private int groupId; // The group ID that is used as the unit of the decal mesh sharing and removing.

        [SerializeField]
        private bool projectionBackside; // This flag indicates whether it is possible to project onto the backside.

        [Tooltip("When this is checked, the decal projection process is started at the instance is created.")]
        [SerializeField]
        private bool
            launchOnAwake; // When an instance is created, the decal projection process also starts automatically.。

        [SerializeField]
        private UnityEvent<State> onFinishedLaunch; //　The event is called when decal projection is finished.

        private DecalSpace _decalSpace;

        // The handle of the currently scheduled job stage. The main thread polls it (or completes it
        // synchronously when measuring). See IsWorkerThreadRunning for why the launcher needs it.
        private JobHandle _currentJobHandle;
        private bool _jobsScheduled;
        // The pooled source mesh the current launch's jobs are reading, pinned so the pool does not dispose
        // its NativeArrays while the jobs run.
        private ReceiverConvexPolygonsMesh _currentSource;

        /// <summary>
        ///     True while this projector's jobs are scheduled and not yet completed.
        /// </summary>
        /// <remarks>
        ///     Destroying the projector stops its coroutine but not the scheduled jobs, which write to the
        ///     pipeline's pooled buffers. Starting the next launch in that state would corrupt those buffers,
        ///     so DecalProjectorLauncher must wait until the jobs finish. The C# instance is still readable
        ///     after the Unity object is destroyed. OnDestroy also completes the jobs to release the pool.
        /// </remarks>
        internal bool IsWorkerThreadRunning => _jobsScheduled && !_currentJobHandle.IsCompleted;

        /// <summary>
        ///     State of decal projector.
        /// </summary>
        public State NowState { get; private set; } = State.NotLaunch;

        /// <summary>
        ///     The list of decal mesh that has been generated by the projector.
        /// </summary>
        public List<DecalMesh> DecalMeshes { get; } = new List<DecalMesh>();

        private void Start()
        {
            if (launchOnAwake) Launch(null);
        }

        private void OnDestroy()
        {
            // The coroutine is stopped by the destruction, but the scheduled jobs are not, and they write to
            // the pipeline's pooled buffers. Complete them here so the next launch can reuse the pool safely.
            if (_jobsScheduled)
            {
                _currentJobHandle.Complete();
                _jobsScheduled = false;
            }

            // Release the pinned source so the pool can dispose it.
            if (_currentSource != null)
            {
                _currentSource.InUse = false;
                _currentSource = null;
            }

            // It may be deleted without completing the projection, so we finish it here too.
            // No geometry rollback is needed: the new pipeline appends to the decal meshes only on the main
            // thread after the jobs complete, so a canceled launch never leaves half-appended geometry.
            OnFinished(State.LaunchingCanceled);
        }

        private void OnDrawGizmosSelected()
        {
            var cache = Gizmos.matrix;
            Vector3 originPos = transform.position + transform.forward * depth * 0.5f;
            Gizmos.matrix = Matrix4x4.TRS(originPos, transform.rotation, Vector3.one);
            // Draw the decal box.
            Gizmos.DrawWireCube(Vector3.zero, new Vector3(width, height, depth));
            Gizmos.matrix = cache;
            Gizmos.color = Color.white;
            // Draw the arrow of the projection's direction.
            var arrowLength = depth * 2.0f;
            var arrowStart = transform.position;
            var arrowEnd = transform.position + transform.forward * arrowLength;
            Gizmos.DrawLine(arrowStart, arrowEnd);
            Vector3 arrowTangent;
            if (Mathf.Abs(transform.forward.y) > 0.999f)
                arrowTangent = Vector3.Cross(transform.forward, Vector3.right);
            else
                arrowTangent = Vector3.Cross(transform.forward, Vector3.up);
            var rotAxis = Vector3.Cross(transform.forward, arrowTangent);
            var rotQuat = Quaternion.AngleAxis(45.0f, rotAxis.normalized);
            var arrowLeft = rotQuat * transform.forward * arrowLength * -0.2f;
            Gizmos.DrawLine(arrowEnd, arrowEnd + arrowLeft);
            rotQuat = Quaternion.AngleAxis(-45.0f, rotAxis.normalized);
            var arrowRight = rotQuat * transform.forward * arrowLength * -0.2f;
            Gizmos.DrawLine(arrowEnd, arrowEnd + arrowRight);
            Gizmos.matrix = cache;
        }

        private void OnFinished(State finishedState)
        {
            if (onFinishedLaunch == null) return;

            onFinishedLaunch.Invoke(finishedState);
            NowState = finishedState;
            onFinishedLaunch = null;
        }

        /// <summary>
        ///     Execute projection decal to mesh.
        /// </summary>
        /// <remarks>
        ///     This process is performed over multiple frames.
        ///     Projection completion can be monitored using callback functions or by checking the NowState property.
        /// </remarks>
        private IEnumerator ExecuteLaunch()
        {
            InitializeOriginAxisInDecalSpace();

            foreach (var receiverObject in receiverObjects)
            {
                if (receiverObject == null || !receiverObject) continue;

                var receiverDecalMeshes = new List<DecalMesh>();
                AirStickerSystem.CollectEditDecalMeshes(receiverDecalMeshes, receiverObject, decalMaterial, groupId);
                DecalMeshes.AddRange(receiverDecalMeshes);

                var skinnedMeshRenderers = receiverObject.GetComponentsInChildren<SkinnedMeshRenderer>()
                    .Where(s => s.name != "AirStickerRenderer").ToArray();
                var terrains = receiverObject.GetComponentsInChildren<Terrain>();

                if (AirStickerSystem.ReceiverObjectTrianglePolygonsPool.Contains(receiverObject) == false)
                {
                    // New receiver object: extract its source triangle polygons (frame-sliced).
                    var resultHolder = new ReceiverConvexPolygonsMesh[1];
                    yield return AirStickerSystem.BuildTrianglePolygonsFromReceiverObject(
                        receiverObject.GetComponentsInChildren<MeshFilter>(),
                        receiverObject.GetComponentsInChildren<MeshRenderer>(),
                        skinnedMeshRenderers,
                        terrains,
                        resultHolder);

                    if (resultHolder[0] == null)
                    {
                        // A receiver mesh is not Read/Write enabled, so there is nothing to build.
                        OnFinished(State.LaunchingCanceled);
                        yield break;
                    }

                    AirStickerSystem.ReceiverObjectTrianglePolygonsPool.RegisterTrianglePolygons(
                        receiverObject, resultHolder[0]);
                }

                if (!receiverObject)
                {
                    OnFinished(State.LaunchingCanceled);
                    yield break;
                }

                var source = AirStickerSystem.GetTrianglePolygonsFromPool(receiverObject);
                if (source == null)
                {
                    OnFinished(State.LaunchingCanceled);
                    yield break;
                }

                var pipeline = AirStickerSystem.JobPipeline;
                var trans = transform;
                // basePosition is the center of the decal box.
                var centerPositionOfDecalBox = trans.position + trans.forward * (depth * 0.5f);

                // Segment 1: skinning + broad phase + clip (parallel jobs).
                source.InUse = true;
                _currentSource = source;
                _currentJobHandle = pipeline.ScheduleClipStage(
                    source, centerPositionOfDecalBox,
                    _decalSpace.Ex, _decalSpace.Ey, _decalSpace.Ez,
                    width, height, depth, projectionBackside);
                _jobsScheduled = true;
                JobHandle.ScheduleBatchedJobs();
                yield return CompleteJobHandle("clip stage (skinning + broad phase + clip)");

                if (!receiverObject)
                {
                    _jobsScheduled = false;
                    source.InUse = false;
                    _currentSource = null;
                    OnFinished(State.LaunchingCanceled);
                    yield break;
                }

                // Main-thread step between the segments: size the output from the clip result.
                pipeline.CountBuild(source, receiverDecalMeshes);

                // Segment 2: build the appended geometry (serial job, off the main thread).
                _currentJobHandle = pipeline.ScheduleBuildStage(
                    source, centerPositionOfDecalBox, _decalSpace.Ex, _decalSpace.Ey,
                    width, height, zOffsetInDecalSpace);
                JobHandle.ScheduleBatchedJobs();
                yield return CompleteJobHandle("build stage (fan + uv + tangent)");
                _jobsScheduled = false;
                source.InUse = false;
                _currentSource = null;

                // Merge the built geometry into the decal meshes and upload them (main thread).
                pipeline.ApplyToDecalMeshes(receiverDecalMeshes);
                foreach (var decalMesh in receiverDecalMeshes) decalMesh.ExecutePostProcessingAfterWorkerThread();
            }

            OnFinished(State.LaunchingCompleted);
            yield return null;
        }

        /// <summary>
        ///     Wait for the current job stage. When performance logging is enabled the handle is completed
        ///     synchronously so the actual job compute time is measured; otherwise the main thread polls the
        ///     handle across frames without blocking.
        /// </summary>
        private IEnumerator CompleteJobHandle(string label)
        {
            if (AirStickerPerformanceLog.Enabled)
            {
                var sw = System.Diagnostics.Stopwatch.StartNew();
                _currentJobHandle.Complete();
                sw.Stop();
                Debug.Log($"[AirSticker][Perf] {label}: {sw.Elapsed.TotalMilliseconds:F2} ms");
            }
            else
            {
                while (!_currentJobHandle.IsCompleted) yield return null;
                _currentJobHandle.Complete();
            }
        }

        /// <summary>
        ///     Create and add AirStickerProjector to the GameObject.
        /// </summary>
        /// <param name="owner">Game object to which the component will be added.</param>
        /// <param name="receiverObject">Receiver object to which decal is applied.</param>
        /// <param name="decalMaterial">Decal material applied to receiver object.</param>
        /// <param name="width">Width of projector. It means to projection range.</param>
        /// <param name="height">Height of projector. It means to projection range.</param>
        /// <param name="depth">Depth of projector. It means to projection range.</param>
        /// <param name="launchOnAwake">
        ///     If it is true, the decal projection is started at same time as additional component.
        ///     If it is false, the decal projection is started by explicitly calling the Launch method.
        /// </param>
        /// <param name="onCompletedLaunch">Callback function called when decal projection is complete.</param>
        /// <param name="zOffsetInDecalSpace">The Z offset of the decal space from the receiver surface.</param>
        /// <param name="groupId">
        ///     The group ID of the decal mesh. <br />
        ///     Decal meshes are shared only within the same group,
        ///     so decals can be removed by group using the RemoveDecalMeshes method. <br />
        ///     If it is not specified, the decal belongs to the group 0.
        /// </param>
        public static AirStickerProjector CreateAndLaunch(
            GameObject owner,
            GameObject receiverObject,
            Material decalMaterial,
            float width,
            float height,
            float depth,
            bool launchOnAwake,
            UnityAction<State> onCompletedLaunch,
            float zOffsetInDecalSpace = 0.005f,
            int groupId = 0)
        {
            var projector = owner.AddComponent<AirStickerProjector>();
            projector.width = width;
            projector.height = height;
            projector.depth = depth;
            projector.zOffsetInDecalSpace = zOffsetInDecalSpace;
            projector.receiverObjects = new GameObject[1];
            projector.receiverObjects[0] = receiverObject;
            projector.decalMaterial = decalMaterial;
            projector.groupId = groupId;
            projector.launchOnAwake = false;
            projector.onFinishedLaunch = new UnityEvent<State>();

            if (launchOnAwake)
                projector.Launch(onCompletedLaunch);
            else if (onCompletedLaunch != null) projector.onFinishedLaunch.AddListener(onCompletedLaunch);

            return projector;
        }

        /// <summary>
        ///     Remove the decal meshes that belong to the specified group.
        /// </summary>
        /// <remarks>
        ///     The decal meshes are removed from the pool and their renderers are destroyed. <br />
        ///     This method should be called after the projectors of the target group
        ///     have finished launching (LaunchingCompleted). <br />
        ///     If it is called while a projector of the target group is launching,
        ///     the launching result is undefined.
        /// </remarks>
        /// <param name="groupId">The group ID of the decal meshes to be removed.</param>
        /// <param name="receiverObject">
        ///     If it is not null, only the decal meshes projected to this receiver object are removed.
        /// </param>
        /// <param name="decalMaterial">
        ///     If it is not null, only the decal meshes using this decal material are removed.
        /// </param>
        public static void RemoveDecalMeshes(
            int groupId,
            GameObject receiverObject = null,
            Material decalMaterial = null)
        {
            AirStickerSystem.DecalMeshPool?.RemoveDecalMeshes(groupId, receiverObject, decalMaterial);
        }

        /// <summary>
        ///     Start projection decal.
        /// </summary>
        /// <remarks>
        ///     This processing is async, so the projection decal takes several frames to finish.
        ///     If you want to monitor the decal projection process, should be using a callback function.
        /// </remarks>
        public void Launch(UnityAction<State> onFinishedLaunch)
        {
            if (NowState != State.NotLaunch)
                Debug.LogError("This function can be called only once, but it was called multiply.");

            NowState = State.Launching;
            if (onFinishedLaunch != null) this.onFinishedLaunch.AddListener(onFinishedLaunch);
            // Request the launching of the decal.
            AirStickerSystem.DecalProjectorLauncher.Request(
                this,
                () =>
                {
                    if (receiverObjects != null)
                        StartCoroutine(ExecuteLaunch());
                    else
                        // Receiver object has been dead, so process is terminated.
                        OnFinished(State.LaunchingCanceled);
                });
        }

        private void InitializeOriginAxisInDecalSpace()
        {
            var trans = transform;
            _decalSpace = new DecalSpace(trans.right, trans.up, trans.forward * -1.0f);
        }
    }
}
